=== jesfre/dtf/dtf-project-archetype/src/test/resources/GlobalConfiguration.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dtfConfig (seleniumHost,seleniumPort,timeout,speed,browser,url,user,password,testsuiteList)>
<!ELEMENT seleniumHost (#PCDATA)>
<!ELEMENT seleniumPort (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT speed (#PCDATA)>
<!ELEMENT browser (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT password (#PCDATA)> 

<!ELEMENT testsuiteList (testsuite+)> 

<!ELEMENT testsuite (suiteName,fileName,dbSnapshot,dbRestore,run)>
 
<!ELEMENT suiteName (#PCDATA)>
<!ELEMENT fileName (#PCDATA)>
<!ELEMENT dbSnapshot (#PCDATA)>
<!ELEMENT dbRestore (#PCDATA)>
<!ELEMENT run (#PCDATA)>

=== jesfre/dtf/dtf-project-archetype/src/test/resources/config/globalConfiguration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dtfConfig SYSTEM "GlobalConfiguration.dtd" >

<!-- 
Developed by Dextra Technologies www.dextratech.com 
-->

<!--
Browser
*firefox C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe
*chrome 
*iexploreproxy
*googlechrome C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe
*mock
*firefoxproxy
*pifirefox
*iexplore
*firefox3
*safariproxy
*konqueror
*firefox2
*safari
*piiexplore
*firefoxchrome
*opera
*iehta
*custom 
 -->
<dtfConfig>
	<seleniumHost>localhost</seleniumHost>
	<seleniumPort>4444</seleniumPort>
	<timeout>80000</timeout>
	<speed>500</speed>
	<browser>*googlechrome C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe</browser>
	<url>localhost:8090/idverification/</url>
	<user>null</user>
	<password>null</password>
	<testsuiteList>
		<testsuite>
			<suiteName>test1</suiteName>
			<fileName>null</fileName>
			<dbSnapshot>false</dbSnapshot>
			<dbRestore>false</dbRestore>
			<run>true</run>
		</testsuite>
		<!-- 
		<testsuite>
			<suiteName>preferencias_asignar_alias_2</suiteName>
			<fileName>null</fileName>
			<dbSnapshot>false</dbSnapshot>
			<dbRestore>false</dbRestore>
			<run>true</run>
		</testsuite>
		<testsuite>
			<suiteName>preferencias_asignar_alias</suiteName>
			<fileName>preferencias_asignar_alias.html</fileName>
			<dbSnapshot>false</dbSnapshot>
			<dbRestore>false</dbRestore>
			<run>false</run>
		</testsuite>
		<testsuite>
			<suiteName>admin_usuarios_alta</suiteName>
			<fileName>admin_usuarios_alta.html</fileName>
			<dbSnapshot>false</dbSnapshot>
			<dbRestore>false</dbRestore>
			<run>false</run>
		</testsuite>
		<testsuite>
			<suiteName>cambiar_empresa</suiteName>
			<fileName>cambiar_empresa.html</fileName>
			<dbSnapshot>false</dbSnapshot>
			<dbRestore>false</dbRestore>
			<run>false</run>
		</testsuite>
		 -->
	</testsuiteList>
</dtfConfig>
